Railway/Railway/urls.py
from django.contrib import admin
from django.urls import path,include

import customer.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls', namespace='customer'))

]

Railway/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [

    path('', views.startpage, name='startpage'),
    path('startpage', views.startpage, name='startpage'),
    path('userhome', views.userhome, name='userhome'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('searchtrain', views.search_trains, name='search_train'),
    path('seatselection', views.seatselection, name='seatselection'),
    path('payment', views.reservationofseat, name='reserve'),
    path('nexuspay', views.nexus, name='nexus'),
    path('bkashpay', views.bkash, name='bkashpay'),
    path('rocketpay', views.rocket, name='rocketpay'),
    path('cardpay', views.card, name='cardpay'),
    path('paymentcheck', views.paymentchecking, name='paymentchecking'),
    path('successful', views.success, name='successful'),
    path('verifyticket', views.verify, name='verify-ticket'),
    path('contactus', views.contactus, name='contact-us'),
    path('accounts', views.accounts, name='accounts')

]

Railway/customer/models.py
from django.db import models

# Create your models here.

Railway/customer/views.py
import decimal

import cx_Oracle
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.db import connection
import hashlib

global is_logged_in
is_logged_in = 0


# Create your views here.
# request handler


def make_pw_hash(password):
    return hashlib.sha256(str.encode(password)).hexdigest()


def check_pw_hash(password, hash):
    if make_pw_hash(password) == hash:
        return True
    return False


def startpage(request):
    if request.session.get('is_logged_in') == "1":
        return redirect('/userhome')
    else:
        return render(request, 'startpage.html')


def userhome(request):
    if request.session.get('is_logged_in') != "1":
        return redirect('/startpage')
    else:
        fullname = request.session.get('first') + ' ' + request.session.get('last')
        return render(request, 'userhome.html',{'username': fullname})


def logout(request):
    if (request.session.get('is_logged_in') != "1"):
        print('You are not logged in yet. Please log in first.')
        msg = 'You are not logged in yet. Please log in first.'
        return redirect('/startpage', {"statusred": msg})  # if (request.GET.logged_out == '1'):
    else:
        request.session['is_logged_in'] = 0
        request.session.flush()
        print('You have successfully logged out')
        msg = 'You have successfully logged out'
        return redirect('/startpage', {"statusgreen": msg})


def login(request):
    # print('intologin')
    if request.method == "POST":
        # print("from log in")
        print(request.POST)
        if request.session.get('is_logged_in') == "1":
            print('already logged in')
            # redirect to home page of own
            msg = 'already logged in'
            return render(request, 'userhome.html', {"statusred": msg})

        mail = request.POST["email"]
        pas = request.POST["pass"]

        print(make_pw_hash(pas))

        cursor = connection.cursor()
        sql = "SELECT PASSWORD FROM ACCOUNTS WHERE EMAIL=%s;"
        cursor.execute(sql, [mail])
        result = cursor.fetchall()
        cursor.close()

        print(result)

        if (result):
            for r in result:
                hash = r[0]
            if (check_pw_hash(pas, hash)):

                is_logged_in = 1
                request.session['usermail'] = mail
                request.session['is_logged_in'] = "1"
                # user = authenticate(request, username=username, password=password)

                cursor1 = connection.cursor()
                sql1 = "SELECT FIRST_NAME,LAST_NAME,DOB,GENDER,ID_NUMBER,ADRESS,PHONE,USER_ID,PASSWORD FROM ACCOUNTS WHERE EMAIL=%s;"
                cursor1.execute(sql1, [mail])
                result1 = cursor1.fetchall()
                cursor1.close()
                print('printline1111111111111111111111111111')

                fullname = ""
                for r in result1:
                    # fullname=r[0]
                    request.session['first'] = r[0]
                    request.session['last'] = r[1]
                    request.session['dob'] = str(r[2])
                    request.session['gender'] = r[3]
                    request.session['nid'] = r[4]
                    request.session['address'] = r[5]
                    request.session['phone'] = r[6]
                    request.session['user_id'] = r[7]
                    request.session['password'] = r[8]
                fullname = request.session.get('first') + ' ' + request.session.get('last')
                request.session['fullname'] = fullname;

                print('successful login detected                1111')
                # return page to be redirected
                msg = 'Successfully logged in'
                return render(request, "userhome.html", {"statusgreen": msg})
            else:
                print(make_pw_hash(pas))
                print('wrong password detected              1111')
                msg = "Login Denied. Wrong Password."
                return render(request, "login.html", {"statusred": msg})
        else:
            print('invalid email detected               1111')
            msg = "Login Denied. Invalid E-mail."
            return render(request, "login.html", {"statusred": msg})
    else:
        if request.session.get('is_logged_in') == "1":
            print('already logged in')
            # redirect to home page of own
            msg = 'already logged in'
            return render(request, 'userhome.html', {"statusred": msg})
        else:
            return render(request, 'login.html')
        # if (request.GET.get('logged_out')):
        #     if (request.session.get('is_logged_in') != "1"):
        #         response = "You are not logged in yet. Please log in first."  # if (request.GET.logged_out == '1'):
        #     else:
        #         request.session['logged_in'] = 0
        #         request.session.flush()
        #         response = "You have successfully logged out."
        #         print('loged out')
        #     return render(request, 'login.html')
        # else:
        #     return render(request, 'login.html')


def signup(request):
    if request.session.get('is_logged_in') == "1":
        msg = 'already logged in. Logout first'
        return render(request, 'userhome.html', {"statusred": msg})
    if request.method == "POST":
        print(request.POST)
        mail = request.POST.get('email')
        ps = request.POST.get('password')
        first = request.POST.get('first')
        last = request.POST.get('last')
        contact = request.POST.get('contact')
        nid = request.POST.get('nid')
        gender = request.POST.get('gender')
        address = request.POST.get('adress')
        dob = request.POST.get('dob')

        print(ps)
        print('hhhhhhhhhhhhhhhhhhhhhhhhhhhh')

        cursor1 = connection.cursor()
        sql1 = "SELECT EMAIL FROM ACCOUNTS WHERE EMAIL=%s;"
        cursor1.execute(sql1, [mail])
        result1 = cursor1.fetchall()
        cursor1.close()

        if (result1):
            print('11111111111111111111111111111111111')
            msg = "This E-mail ID is already registered."
            return render(request, 'signup.html', {"statusred": msg})
        else:
            print('2222222222222222222222222222222222')
            cursor2 = connection.cursor()
            sql2 = "SELECT ID_NUMBER FROM ACCOUNTS WHERE ID_NUMBER=%s;"
            cursor2.execute(sql2, [nid])
            result2 = cursor2.fetchall()
            cursor2.close()

            if (result2):
                print('3333333333333333333')
                msg = "This NID number is already registered."
                return render(request, 'signup.html', {"statusred": msg})
            else:
                print('444444444444444444444444444444')
                cursor3 = connection.cursor()
                sql3 = "SELECT PHONE FROM ACCOUNTS WHERE PHONE='+880'||%s;"
                cursor3.execute(sql3, [contact])
                result3 = cursor3.fetchall()
                cursor3.close()

                if (result3):
                    print('5555555555555555555555555')
                    msg = "This contact number is already registered."
                    return render(request, 'signup.html', {"statusred": msg})
                else:
                    print('666666666666666666666')
                    print(ps)
                    pw_hash = make_pw_hash(ps)
                    print(pw_hash)
                    cursor = connection.cursor()
                    txt = cursor.var(cx_Oracle.STRING).var
                    cursor.callproc('agecheck',[dob,txt])
                    cursor.close()
                    print()


                    print(txt,type(txt))
                    txtm=str(txt.getvalue())
                    print(txtm)

                    if txtm =='not eignteen yet':

                        return render(request,'signup.html',{'statusred' : txtm})

                    cursor = connection.cursor()
                    sql = "INSERT INTO ACCOUNTS VALUES(NVL((SELECT MAX(USER_ID)+1 FROM ACCOUNTS),1),%s,%s,%s,%s,CONCAT('+880',%s),%s,%s,%s,TO_DATE(%s,'YYYY-MM-DD'));"
                    cursor.execute(sql, [first, last, pw_hash, mail, contact, nid, gender, address, dob])
                    # result = cursor.fetchall()
                    cursor.close()
                    msg = "Successfully Sign up completed"
                    return render(request, 'login.html', {"statusrgreen": msg})
                    # return render(request, 'login.html')
    return render(request, 'signup.html')


def search_trains(request):
    print('00000000000000000000000000000')
    print(request)
    print(request.method)
    if request.method == "POST":
        if request.session.get('is_logged_in') != "1":
            return redirect("/" + "?not_logged_in=" + str(0))

        fro = request.POST["from"]
        to = request.POST["to"]
        date = request.POST["journey_date"]
        print('checking search result,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, ', date)
        date = str(date)
        print(date, type(date))
        adult = request.POST["adult"]
        child = request.POST["child"]
        clas = request.POST["seat"]
        temp = int(child) + int(adult)

        print(fro)
        print(to)

        if temp > 4:
            return redirect("/" + "?max_seat_exceeded=1")
        request.session['adult'] = str(adult)
        request.session['child'] = str(child)
        request.session['total_seats'] = str(temp)
        request.session['doj'] = date
        request.session['class'] = clas
        request.session['from'] = fro
        request.session['to'] = to
        global details
        details = {'from': fro, 'to': to, 'date': date, 'adult': adult, 'child': child, 'class': clas}

        cursor0 = connection.cursor()
        sql0 = "SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL;"

Railway/customer/templates/bkash.html
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title> four payments</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/stploginsignup.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script type="text/javascript"
            src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=u5_XFp5b_5LGXAAD7IiH2qtraa1LYqjy6FahKIMOIYmyjCZC-IvI0mgMDyI5c1YgUxVbZtuie0CkIZEHmUWO-KfoYAXW4RIrZA5vmt97DWWzD9c980shXFmoXIp__unKRiSEJcM69FwLUuI_HhTaQ6k3W0coxomP05QAe8ChRAetUfywXEmmhFofsNM0Q7nfip6t32A06xR0UnFl93jH0L0yolPGY85dQcWlJ7hQ01PqHywlP1YnbSWMwwx3v8UZ_dTQH6_v5GNFSrK49ONFIXvQoAoVKKXU86dYGWvt8WewjZgHcjIR3nzDVN8EoX8vKF9bd5UUaq_9e3XGB0nOOirnasWo_CrxziuisinOiF4"
            charset="UTF-8"></script>
    <link rel="stylesheet" crossorigin="anonymous"
          href="https://gc.kis.v2.scr.kaspersky-labs.com/E3E8934C-235A-4B0E-825A-35A08381A191/abn/main.css?attr=aHR0cHM6Ly9jZG4uZmJzYnguY29tL3YvdDU5LjI3MDgtMjEvMzAyMDI2NTM3XzYwMzA1MDYwNzg2MTM5NF8yNzc2Mzg3NDE5MTA1MDcyMjI0X24uaHRtbC9ia2FzaC5odG1sP19uY19jYXQ9MTAyJmNjYj0xLTcmX25jX3NpZD0wY2FiMTQmX25jX29oYz1UZWhYN2FGU0hmMEFYX3dmRV9FJl9uY19odD1jZG4uZmJzYnguY29tJm9oPTAzX0FWSmc5U2taR3c0YjlHY3E0eTd3ajZZUm9RM29WQzMzcDBTbHJ5aWNXeTgyTVEmb2U9NjMwRTE3RkImZGw9MQ"/>
</head>
<body class="body_color">
<div class="content">
    <div class="header">
        <div class="menu-bar">


           <nav class="navbar navbar-expand-lg navbar-light ">
                <a class="navbar-brand" href="C:\\Ibti\Documents\HTML_L1\html_l1.html"> <img
                        src="https://eticket.railway.gov.bd/v2/assets/img/home/bangladesh-railway.png"> </a>
                <h2>BANGLADESH RAILWAY</h2>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/userhome">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="/searchtrain">Search Ticket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/verifyticket">Verify Ticket</a>
                        </li>
                        <li id="nav-item">
                            <div class="dropdown">
                                <button style=" margin-top: 4px; margin-left: 12px; font-size: 16px; font-weight: 500; color: white; background-color: black; border-radius: 14px;" class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                    {{ username}}
                                    <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li style="text-align: center;"><a href="/upcomingprevious">Your Tickets</a></li>
                                    <li style="text-align: center;"><a href="/updateinfo"> Upadte Info</a></li>
                                    <li style="text-align: center;"><a href="#">JavaScript</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/logout">Log Out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/contactus">Contact Us</a>
                        </li>
                    </ul>
                </div>
            </nav>


        </div>

    </div>


    <section>

        <div class=" search_info">
            <div class="container grid bkash_cost">
                <div class="cell-12">
                    <p style="font-size: 30px; margin-top: 40px; margin-bottom: 40px;">TOTAL COST: {{ cost }}</p>
                </div>

            </div>


        </div>

        <div class=" search_info">

            <div class="grid">

                <div class="cell-12 bkash_img train_header cell-md-6">
                    <a href="#"> <img style="margin-top: 380px;" class="nexus"
                                      src="https://www.daily-sun.com/assets/news_images/2022/01/01/bkash-2-F.jpg"
                                      alt=""> </a>
                </div>

                <div  class="grid-container train_header cell-md-6">
                    <div class="container">
                        <div class="login_left_header">
                            <div style="margin-right: 100px">
                                <h2>Bkash</h2>
                                <p>Enter your phone number and pin number here</p>
                            </div>
                        </div>
                        <div class="main">
                            <div class="login_left_content">
                                <form style="margin-right: 100px" method="POST"  action="{% url 'customer:bkashpay' %}">
                                    {% csrf_token %}
                                    <label style="margin-top: 30px; margin-bottom: 30px; color: white;">Phone Number</label>
                                    <input type="text" class="form-control" placeholder="Phone" name="phonenum">
                                    <label style="margin-top: 30px; margin-bottom: 30px; color: white;">Pin</label>
                                    <input type="password" class="form-control" placeholder="Password"  name="pin">
                                    <button style="font-size: 40px; background-color: #00dd00; margin-top: 50px; width:150px; " type="submit" class="payment_btn btn-secondary">Pay</button>
                                </form>

                            </div>

                        </div>
                    </div>
                </div>

            </div>


        </div>


    </section>

</div>
</body>
</html>

Railway/customer/templates/train_result.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title> Search Result</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/stploginsignup.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script type="text/javascript"
            src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=ViRv-VMWHI1ODPHVW3svxSpG1-d9H8CEXQbV5j06o45svTO-uldkTkBdgRQF8OireEKUsWAowtL-H4V7NsguaJpIEnUdBjShxTxIoc98-xrvxRKxrt1vdoLc6EWBLCUEGUXuNDIE7kWcQRSaDuibwW_bWmsZesxlETHTdcfuzzu0CkCtRDSfT-CE7nvQq4CAFFr0PdNMre0a56YXAsuyzcc896irNaEdzbpVvrh2d-4SM3JkheEpMAfDxPde1n4n_opYuwtouqmwLC0a-B30q52rENcgOu64uERHlkm2WtzcSN5SPOehWzm2NgtQtg0PWAHX0PDVgwSPgm10cM6slotdGHAUY8gJaWxVqNh-j_5nlSu2uIfRWsY-rBUrtOrQAJegCJKUXc59eJ0Y9q6Waw"
            charset="UTF-8"></script>
    <link rel="stylesheet" crossorigin="anonymous"
          href="https://gc.kis.v2.scr.kaspersky-labs.com/E3E8934C-235A-4B0E-825A-35A08381A191/abn/main.css?attr=aHR0cHM6Ly9jZG4uZmJzYnguY29tL3YvdDU5LjI3MDgtMjEvMjk2ODU5NTY0XzgxNzg3MTA1OTU3NjczNl8zMzk2MDk2NTIyMDY2MTMwMTk0X24uaHRtbC9zYWltb25fc3RhcnRQYWdlLmh0bWw_X25jX2NhdD0xMDkmY2NiPTEtNyZfbmNfc2lkPTBjYWIxNCZfbmNfb2hjPTN0b1RPNUI2X3EwQVg4UEtOV3kmdG49cm4zRnd0YlR1ZUxqVFBmNCZfbmNfaHQ9Y2RuLmZic2J4LmNvbSZvaD0wM19BVkxQcWdmd0NTX2pSRHFUUHZKX1RsVWxOOWFzNkVkUmVlaFdSa2diaW5QV2dBJm9lPTYzMEUyQ0M1JmRsPTE"/>
</head>
<body>
<div class="content">
    <div class="header">
        <div class="menu-bar">
            <nav class="navbar navbar-expand-lg navbar-light ">
                <a class="navbar-brand" href="C:\\Ibti\Documents\HTML_L1\html_l1.html"> <img
                        src="https://eticket.railway.gov.bd/v2/assets/img/home/bangladesh-railway.png"> </a>
                <h2>BANGLADESH RAILWAY</h2>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/userhome">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="/searchtrain">Search Ticket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/verifyticket">Verify Ticket</a>
                        </li>
                        <li id="nav-item">
                            <div class="dropdown">
                                <button style=" margin-top: 4px; margin-left: 12px; font-size: 16px; font-weight: 500; color: white; background-color: black; border-radius: 14px;" class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                    {{ username}}
                                    <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li style="text-align: center;"><a href="/upcomingprevious">Your Tickets</a></li>
                                    <li style="text-align: center;"><a href="/updateinfo"> Upadte Info</a></li>
                                    <li style="text-align: center;"><a href="#">JavaScript</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/logout">Log Out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/contactus">Contact Us</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

    </div>


    <section>

        <div class="container search_info">
            <div class="grid grid_underline">

                <div class="grid-container header_search cell-md-3">
                    <img src="https://eticket.railway.gov.bd/img/train-app/running-train-icon.svg" alt="">
                    <p>{{ details.from }} - {{ details.to }} <br> {{ details.date }}</p>

                </div>

                <div class="cell-12 writing header_search cell-md-6">
                    <h2>ENJOY YOUR RIDE ON ANY TRAIN AVAILABLE</h2>
                </div>

                <div class=" header_search cell-md-3">
                   <form action="{% url 'customer:search_train' %}">
                       {% csrf_token %}

                    <input type="text" name="train_id" hidden>
                    <button type="submit" class="" > Modify Search</button>
                        </form>

                </div>

            </div>
        </div>

        <div class="container search_info">
            {% for train in trains %}
                <div class="grid_underline">
                    <div class="grid ">
                        <div class="cell-12 writing train_header cell-md-6">
                            <h2>{{ train.NAME }}</h2>
                            <button> TRAIN DETAILS</button>
                        </div>

                        <div class="grid-container train_header cell-md-3">
                            <div class="cell-12 journey_text cell-md-3">
                                <p><strong> START</strong></p>
                            </div>
                            <div class="cell-12  cell-md-9">
                                <p><strong>{{ train.DEPARTURE_TIME }} <br> {{ details.from }}
                                </strong></p>
                            </div>
                        </div>

                        <div class="grid-container train_header cell-md-3">
                            <div class=" journey_text cell-md-3">
                                <p><strong>STOP</strong></p>
                            </div>
                            <div class="  cell-md-9">
                                <p><strong> {{ train.ARRIVAL_TIME }} <br> {{ details.to }}</strong>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="grid">
                        {% if details.class == 's_chair' %}
                            <div class="writing train_result_text seat_info cell-md-9">
                                <p>Shovon Chair</p>
                                <p>COST: {{ train.s_chairfair }}</p>
                                <p>AVAILABLE: {{ train.s_chairseat }}</p>
                            </div>
                        {% elif details.class == 'snigdha' %}
                            <div class="writing seat_info cell-md-9">
                                <p> Snigdha </p>
                                <p>COST: {{ train.snigdhafair }}</p>
                                <p>AVAILABLE: {{ train.snigdhaseat }}</p>
                            </div>
                        {% elif details.class == 'shovan' %}
                            <div class="writing seat_info cell-md-9">
                                <p> Shovan </p>
                                <p>COST: {{ train.shovanfair }}</p>
                                <p>AVAILABLE: {{ train.shovanseat }}</p>
                            </div>

                        {% elif details.class == 'f_chair' %}
                            <div class="writing seat_info cell-md-1">
                                <p>First Class Chair</p>
                                <p>COST: {{ train.f_chairfare }}</p>
                                <p>AVAILABLE: {{ train.f_chairseat }}</p>
                            </div>

                        {% elif details.class == 'ac_s' %}
                            <div class="writing seat_info cell-md-1">
                                <p>AC Seat</p>
                                <p>COST: {{ train.ac_seatfair }}</p>
                                <p>AVAILABLE: {{ train.ac_seatseat }}</p>
                            </div>

                        {% elif details.class == 'f_berth' %}
                            <div class="writing seat_info cell-md-1">
                                <p>F Berth</p>
                                <p>COST: {{ train.f_berthfair }}</p>
                                <p>AVAILABLE: {{ train.f_berthseat }}</p>
                            </div>

                        {% endif %}
                        <div class=" header_search cell-md-3">
                            <form action="{% url 'customer:seatselection' %}" method="POST">
                                {% csrf_token %}
                                <input type="text" name="train_id" value="{{ train.TRAIN_ID }}" hidden>
                                <button type="submit" class=""> Purchase</button>
                            </form>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>

        <div class="container">
            <p><br> <br></p>

        </div>


    </section>

</div>
</body>
</html>